### ISSUE TITLE
How to handle dynamic IDs in examples

### ISSUE THREAD

**Issue by oieduardorabelo** [styleguidist/snapguidist#17]
hey guys! :)

i've a few components that generates dynamic internal ids for their children, like:

```jsx
import shortid from 'shortid';

class Field extends React.Component {
  constructor() {
    this.instanceId = shortid.generate();
  }

  render() {
    return (
      <p>
        <label htmlFor={this.instanceId}>Example<label>
        <input id={this.instanceId} />
      <p>
    )
  } 
}
```

Every time I start the style guide, I've a few red bars diffing only the ID.

Without moving it to a prop, there's any solution for this issue?

(I'm not worried about it tbh, just asking :P)

**Comment by MicheleBertoli** [comment]
Hello @oieduardorabelo, thanks for your question.
Snapshots fail with [pseudo-random](https://github.com/styled-components/jest-styled-components/issues/29) values or values that change overtime and, apart from [mocking](https://github.com/facebook/draft-js/issues/702) the source of randomness, there is no solution.
In this case, as you said, the only way is passing the `shortid` generator as prop.
