### ISSUE TITLE
Component gets unmounted = ref is null while I interact with a component

### ISSUE THREAD

**Issue by albinotonnina** [styleguidist/snapguidist#19]
Hello Michele!

I was playing with this example in Styleguidist cookbook: [how-to-use-refs-in-examples](https://react-styleguidist.js.org/docs/cookbook.html#how-to-use-refs-in-examples)

Took me quite a while to understand why the example would not work on my almost clean version of styleguidist + snapguidist.

When I click the button in the even more simplified example below I get an error because snapguidist basically unmount the component so ref gets called with null (is that correct?)[https://github.com/facebook/react/issues/9328#issuecomment-298438237](https://github.com/facebook/react/issues/9328#issuecomment-298438237)

Could this lead to issues? I'm interacting with a component that is unmounted?

Example to try on a clean installation of styleguidist+snapguidist

```js
let myEl;
<div>
  <button onClick={() => myEl.value = 'Pizza'}>Insert</button>
  <input ref={ref => myEl = ref} />
</div>
```

**Comment by MicheleBertoli** [comment]
Good catch, thanks @albinotonnina.
I'll look into it ASAP.

**Comment by MicheleBertoli** [comment]
I started looking into this, and it's a quite interesting issue.
Thank you very much for providing a non-working example.
I'll keep you posted.

**Comment by albinotonnina** [comment]
My pleasure! I love snapguidist, makes my life easier :) I would look at it myself, at least to help, but it's beyond me at the minent :) keep up the great work Michele!

**Comment by MicheleBertoli** [comment]
The problem is related to the `react-test-renderer` (we are using it in an unconventional way).
We faced a similar [issue](https://github.com/facebook/react/issues/8692) a few months ago, it seems React 16 is going to solve the problem.
In the meanwhile, I'll keep on investigating.

**Comment by MicheleBertoli** [comment]
Relevant issue: https://github.com/styleguidist/react-styleguidist/issues/614

**Comment by MicheleBertoli** [comment]
This package has been updated to the latest version of Styleguidist (6.2.2) and React (16.2.0).
The issue is not solved yet (unfortunately), but there's a workaround:
```js
<input ref={ref => ref && (myEl = ref)} />
```

**Comment by albinotonnina** [comment]
Thanks Michele! I would close this. Unless you wanna leave it open in case of a fix! Ciao!

**Comment by MicheleBertoli** [comment]
Although there's no easy way to fix this properly, I'd leave it open so that it can be useful for other people.
Thank you very much, @albinotonnina.

**Comment by goransm** [comment]
I'm not sure if this is in any way related, but I'm having a problem related to react-intl

I created a Wrapper component that works with react-styleguidist, it wraps all components with the required <IntlProvider />

But I get errors from snapguidist : Uncaught Error: [React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry.

It seems like the snapshots are rendered without the styleguidist Wrapper. I don't know if I am doing something wrong, as I can't seem to find others with the same problem. I'd create an issue if I was sure this is really an issue, and not just me messing up the configuration. Any ideas would be appreciated!

**Comment by MicheleBertoli** [comment]
Hello @goransm, this seems a different problem.
Would you mind opening a [new issue](https://github.com/styleguidist/snapguidist/issues/new) and provide a non-working example?
Thank you very much!
