### ISSUE TITLE
Can't resolve 'react-codemirror'

### ISSUE THREAD

**Issue by dbertella** [styleguidist/snapguidist#20]
Hi guys just added snapguidist on my styleguidist and I have to install `react-codemirror` as a dependency in order to make project compile.
Should it need to be added as a dependency into snapguidist perhaps?

**Comment by sapegin** [comment]
For some obscure reason codemirror and react-codemirror are peer dependencies, they should be normal dependencies. 

I also recommend to upgrade to https://github.com/scniro/react-codemirror2.

**Comment by MicheleBertoli** [comment]
The reason is not obscure, `codemirror` and `react-codemirror` used to be dependencies of `styleguidist`, therefore they were peer for `snapguidist`.
We just need to move to `react-codemirror2` as `styleguidist` did, as we don't want have separate dependencies.
Thanks @dbertella.

**Comment by sapegin** [comment]
They are dependencies of Snapguidist and accidentally Styleguidist uses them too. But relaying on that is very fragile ;-)

**Comment by MicheleBertoli** [comment]
The only reason why we decided to use `codemirror` was that `styleguidist` was using it and we wanted to have a consistent UI, nothing accidental.
Anyway, I'll fix it asap or anyone feel free to fix it.
Thanks!

**Comment by sapegin** [comment]
Still there’s no reason to make them peer dependencies ;-)

**Comment by MicheleBertoli** [comment]
Perfect, thanks @sapegin.
