### ISSUE TITLE
Upgrade to react-styleguidist 6.x

### ISSUE THREAD

**Issue by iamtyce** [styleguidist/snapguidist#23]
We've recently upgraded to React Styleguidist [v6.0.24](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.24) and have noticed a small bug with Snapguidist around the colour changes on diffs:

### Before
<img src="https://user-images.githubusercontent.com/433865/30594653-b9e8a6dc-9d1c-11e7-980b-b3e88bb3a840.png" width="400" />

### After
<img src="https://user-images.githubusercontent.com/433865/30594662-c1b6ccc2-9d1c-11e7-9b2c-173e01b393d1.png" width="400" />

We're trying to pin down whether this was due to RSG only supporting Webpack 2 now, some Babel changes or something else entirely.

Everything else with Snapguidist seems to still be functioning perfectly (snapshots, diffs etc) -- it's just the colour that's dropped off.

Would love to raise a PR and help if you can point me in the right direction!

**Comment by iamtyce** [comment]
@MicheleBertoli Are you able to replicate this bug at all?

**Comment by MicheleBertoli** [comment]
Hello @iamtyce thanks for opening this issue.
Sorry for the late answer, but I was abroad for a conference (JSCamp Romania).
I won't be able to repro this until tomorrow but please feel free to submit a PR, I'll be happy to review it.

**Comment by iamtyce** [comment]
@MicheleBertoli No worries, hope JSCamp was fun! 😁 I haven't been able to figure out the source of the issue but would love to see if you can pinpoint the problem..? I'll keep trying today and will comment here if I can find something out.

**Comment by MicheleBertoli** [comment]
Thank you very much @iamtyce.
The issue has something to do with [CodeMirror](https://github.com/styleguidist/snapguidist/blob/master/src/components/Code.js#L17).

When it works (with an old version), the output is the following:

![screen shot 2017-09-26 at 11 27 12 am](https://user-images.githubusercontent.com/1308971/30855722-cf573128-a2ad-11e7-9fe9-72bdc21fd8cf.png)

When it doesn't (current version), the output is the following:

![screen shot 2017-09-26 at 11 26 53 am](https://user-images.githubusercontent.com/1308971/30855717-c9db3122-a2ad-11e7-8609-14d9071b5eda.png)

**Comment by sapegin** [comment]
Looks like you have the same issue: https://github.com/styleguidist/react-styleguidist/issues/611

**Comment by iamtyce** [comment]
@sapegin Thanks for figuring out the bug, much appreciated! I've updated rsg to `6.0.26` and can see I'm now using react-codemirror `2.0.0` but still have the missing CSS issue.

I'm still seeing the following (missing class) markup, too:

`<span role="presentation" style="padding-right: 0.1px;">+ Received</span>`

**Comment by sapegin** [comment]
@iamtyce It should be fixed in Snapguidist too — react-codemirror should be replaced with the latest react-codemirror2.

**Comment by iamtyce** [comment]
Ah, got it! I might raise a PR for @MicheleBertoli now 👍
