### ISSUE TITLE
Hide green/red snapshot bar when condition is set

### ISSUE THREAD

**Issue by iamtyce** [styleguidist/snapguidist#25]
We have a situation where we would like to achieve the following with Snapguidist:

- Hide the green/red snapshot bar for certain components or for an entire section (ie. documentation only components)
- Hide the grey bar when the styleguide is published (in our case to Github pages)

Are there any current config settings that would allow us to do this without some dirty CSS hacks etc?

**Comment by MicheleBertoli** [comment]
Hello @iamtyce, thanks for your feedback.
You can easily achieve the second one, by using a different configuration file for the build (with the `--config` option).

We talked about creating and opt-in/opt-out system with @cef62, but we never had time to build it.
Any PR is much appreciated : )

**Comment by iamtyce** [comment]
Thanks @MicheleBertoli! I'll see if I can attempt the opt-in/out thing next week 😄

**Comment by MicheleBertoli** [comment]
😍
