### ISSUE TITLE
Cannot resolve Playground

### ISSUE THREAD

**Issue by kaisermann** [styleguidist/snapguidist#33]
Hey! I've followed the tutorial to implement snapguidist on my react-styleguidist but I'm gettint the following error when I run the start script:

```
FAIL  Failed to compile

./node_modules/react-styleguidist/lib/rsg-components/Playground/index.js
Module not found: Can't resolve 'rsg-components/Playground/Playground' in '/<path-to-project>/node_modules/react-styleguidist/lib/rsg-components/Playground'
```

Here's the `alias` part of the loaded webpackconfig:

```js
{ entry: 
   [ '/<path-to-project>/packages/css-packs/core-styles/src/index.scss',
     '/<path-to-project>/node_modules/react-styleguidist/lib/index',
     '/<path-to-project>/node_modules/react-dev-utils/webpackHotDevClient.js',
     '!!style-loader!css-loader!codemirror/lib/codemirror.css',
     '!!style-loader!css-loader!rsg-codemirror-theme.css',
     '!!style-loader!css-loader!/<path-to-project>/node_modules/snapguidist/lib/styles.css' ],
  output: 
   { path: '/<path-to-project>/styleguide',
     filename: 'build/[name].bundle.js',
     chunkFilename: 'build/[name].js' },
  resolve: 
   { 
     extensions: 
     [
        '.js',
        '.jsx',
        '.json',
        '.js',
        '.jsx',
        '.ts',
        '.tsx',
        '.json',
        '.less',
        '.scss',
        '.sass',
        '.styl',
        '.css'
      ],
     alias: {
      'rsg-components/Playground/PlaygroundRenderer': 'react-styleguidist/lib/rsg-components/Playground/PlaygroundRenderer',
      'rsg-components/Playground': '/<path-to-project>/node_modules/snapguidist/lib/components/Playground',
      'rsg-components/Preview': '/<path-to-project>/node_modules/snapguidist/lib/components/Preview',
      'rsg-codemirror-theme.css': 'codemirror/theme/base16-light.css',
      react: 'preact-compat',
      'react-dom': 'preact-compat',
      'rsg-components': '/<path-to-project>/node_modules/react-styleguidist/lib/rsg-components' 
    },
  modules: [ './node_modules' ] }
  ...
}
```

(I've used `<path-to-project>` here just to shorten the output)

**Comment by LorinWeb** [comment]
I'm having the same issue

**Comment by MicheleBertoli** [comment]
Hello @kaisermann @LorinWeb, thanks for opening the issue and commenting.
I'm sorry to hear you are experiencing a problem with the library.

Would you be able to provide more information (e.g. version of `react-styleguidist`, `snapguidist`, etc.) and/or a non-working example?
Thank you very much!

**Comment by kaisermann** [comment]
I've cloned the https://github.com/styleguidist/example and added snapguidist in [this repo](https://github.com/kaisermann/snapguidist-minimal)

Just do a `yarn start` and the error should appear.

**Comment by MicheleBertoli** [comment]
Thank you very much, @kaisermann.
It was due to https://github.com/styleguidist/react-styleguidist/commit/06a62e4b7b3c65e9669f5483a065478ebfb3e6b7, and it's now fixed in [v3.1.2](https://github.com/styleguidist/snapguidist/releases/tag/v3.1.2).

**Comment by kaisermann** [comment]
Thanks @MicheleBertoli! 

I've exported my config wrappef within `snapguidist()` and now I'm getting:

![image](https://user-images.githubusercontent.com/12702016/38815900-4fbc2a1a-416b-11e8-821d-2166b5891daa.png)

You think this is a problem with my setup?

**Comment by MicheleBertoli** [comment]
Oh, I'm sorry to hear you still have problems.
I tried [v3.1.2](https://github.com/styleguidist/snapguidist/releases/tag/v3.1.2) on your [example repo](https://github.com/kaisermann/snapguidist-minimal) yesterday and it worked.
Would you be able to provide another non-working example?
Thank you very much!

**Comment by kaisermann** [comment]
Oops, my bad. 

I'm using `preact` with the appropriate `react` alias, but snapguidist uses the fiber API which `preact-compat` doesn't provide: 

```js
var ReactInternals = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;

var ReactCurrentOwner = ReactInternals.ReactCurrentOwner;
var ReactDebugCurrentFrame = ReactInternals.ReactDebugCurrentFrame;
```
