### ISSUE TITLE
Usage with Create React App

### ISSUE THREAD

**Issue by randytorres** [styleguidist/snapguidist#35]
How can I use this with Create React App? I am getting an error ```10 obsolete snapshot files found, press `u` to remove them..```

**Comment by MicheleBertoli** [comment]
This is interesting, I was able to repro @randytorres - thanks for opening the issue.
So, it looks like the Jest config withing CRA finds out the Snapguidist snapshots.
Unfortunately, there's no way to override the Jest configuration (expect from ejecting).
I think the solution would be to remove the [__snapshots__](https://github.com/styleguidist/snapguidist/blob/master/src/core/snapshot.js#L6) folder from this package, would you be happy to work on a PR?

**Comment by YohMer** [comment]
I am ready to send you a PR to fix this. But, changing the snapshots folder name is not an option. Jest fin the snapshot no matter the name of the folder. So, an easy fix is to rename the extension. I've prepared a fix renaming ".snap" by ".snap_" but if you prefer anything else, let me know.

**Comment by YohMer** [comment]
Just found that: https://github.com/facebook/jest/issues/4383
Which let think the issue is not related to CRA but Jest.

**Comment by MicheleBertoli** [comment]
Thank you very much for working on this and providing more information, @YohMer.
If that's the case I would suggest we use `.sg` (**S**nap**G**uidist) as file extension.
