### ISSUE TITLE
not working with flow and create react app

### ISSUE THREAD

**Issue by YohMer** [styleguidist/snapguidist#36]
I tried to use snapguidist  with create react app in a project which include flow type but did not manage to get it work. Not even to get to the point of this issue: https://github.com/styleguidist/snapguidist/issues/35

### 1st try: use the configuration from snapguidist documentation:

    module.exports = snapguidist({
      components: "src/components/**/[A-Z]*.js",
      defaultExample: true,
      webpackConfig: {
        module: {
          rules: [
            {
              test: /\.jsx?$/,
              exclude: /node_modules/,
              loader: "babel-loader"
            },
            {
              test: /\.css$/,
              loader: "style-loader!css-loader"
            }
          ]
        }
      }
    });

=>  FAIL failed to compiled
compiler do not understand the word "type"

### 2nd try: I installed the flow plugin for babel : 

` npm i flow-babel-webpack-plugin`

And add the plugin in the configuration file:

    module.exports = snapguidist({
      components: "src/components/**/[A-Z]*.js",
      defaultExample: true,
      webpackConfig: {
        module: {
          rules: [
            {
              test: /\.jsx?$/,
              exclude: /node_modules/,
              loader: "babel-loader"
            },
            {
              test: /\.css$/,
              loader: "style-loader!css-loader"
            }
          ]
        },
        plugins: [new FlowBabelWebpackPlugin()]
      }
    });

=> styleguidist start and freeze, server never stop neither any message appears.

Is there a way to get snapguidist working with create-react-app and flow?

**Comment by MicheleBertoli** [comment]
Hello @YohMer, thanks for opening this issue.
I just tried to use CRA + Flow with Snapguidist and it seems to work.

Repro:
- `yarn create react-app whatever`
- `cd whatever`
- [Follow these steps to add Flow to CRA](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow)
- `yarn add --dev react-styleguidist snapguidist`
- Create a config file:

```js
// styleguide.config.js

module.exports = require('snapguidist')();
```

- Create an example:

```js
// Button.js

// @flow

import React from 'react'

type Props = {
  text: string,
}

function Button(props: Props) {
  return <button>{props.text}</button>
}

export default Button
```

```
// Button.md 

Button example:

<Button text="🍕" />
```

- Run`npx styleguidist server`
- Snapguidist works:

<img width="988" alt="screen shot 2018-08-13 at 10 39 28 am" src="https://user-images.githubusercontent.com/1308971/44021484-3902b0b4-9ee5-11e8-8a81-1412e5dd9ff7.png">

At this point, you would experience the issue described in https://github.com/styleguidist/snapguidist/issues/35.
I hope this helps.

**Comment by YohMer** [comment]
Thanks.
Would be nice to add a line in the README for the CRA user.
For the https://github.com/styleguidist/snapguidist/issues/35 issue, I m going to have a look to replace the snap extension by another extension.
